#spring:
#  application:
#    name: ccread-admin
#  datasource:
#    password: "123456"
#    username: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/ccread_cloud?serverTimezone=GMT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
#  cloud:
#    nacos:
#      discovery:
#        server-addr: http://192.168.88.151:8848
#
#server:
#  port: 8002